version: 2
jobs:
  deploy:
    docker:
      - image: docker:git
    steps:
    - checkout
    - run: docker build -t public-tree-map:latest .
    - run: docker build -t public-tree-map-prod:latest .
    - run: docker run --rm -t public-tree-map-prod:latest make deploy GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
    - run: |
        echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
        gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
    - run: gsutil cp -Z build/data/map.json gs://public-tree-map/data/
    - run: gsutil -m cp -Z build/data/trees/*.json gs://public-tree-map/data/trees/
    - run: gsutil setmeta -h "Cache-Control:public, max-age=43200" gs://public-tree-map/data/map.json
    - run: gsutil -m setmeta -h "Cache-Control:public, max-age=43200" gs://public-tree-map/data/trees/*.json
    - run: gsutil -m cp -r build/img gs://public-tree-map/
    - store_artifacts:
        path: tmp/log.txt
        destination: log.txt
workflows:
  version: 2
  commit:
    jobs:
    - deploy:
        filters:
          branches:
            only:
            - master
            - test-circleci
  nightly:
    triggers:
    - schedule:
        cron: 0 8 * * *
        filters:
          branches:
            only:
            - master
    jobs:
    - deploy
