version: 2

jobs:
  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y build-essential
      - run: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
      - run: ./python-env.sh
      - run: echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
      - run: echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
      - run: echo 'export PATH="$HOME/miniconda/bin:$PATH"' >> $BASH_ENV
      - run: echo 'source activate public-tree-map' >> $BASH_ENV
      - run: nvm install 9.11.1
      - run: nvm use 9.11.1
      - run: npm install
      - run: make release
      - run: scripts/upload_trees_google_storage.sh "${GCLOUD_SERVICE_KEY}" "${GOOGLE_PROJECT_ID}" "${CIRCLE_BRANCH}"

      - store_artifacts:
          path: tmp/log.txt
          destination: log.txt

workflows:
  version: 2
  commit:
    jobs:
      - deploy:
          filters:
            branches:
              only:
              - master
              - test-circleci
  nightly:
    triggers:
      - schedule:
          # Midnight PST is 8am UTC
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - deploy
