version: 2

jobs:
  deploy:
    docker:
      - image: publictreemap/public-tree-map:0.0.1
    steps:
      - checkout
      - run: ln -s /public-tree-map/node_modules ./node_modules
      - run: make release
      - run: echo ${GCLOUD_SERVICE_KEY} | gcloud auth activate-service-account --key-file=-
      - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run: gsutil cp -Z build/data/map.json gs://public-tree-map/data/
      - run: gsutil -m cp -Z build/data/trees/*.json gs://public-tree-map/data/trees/
      - run: gsutil setmeta -h "Cache-Control:public, max-age=43200" gs://public-tree-map/data/map.json
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=43200" gs://public-tree-map/data/trees/*.json
      - run: gsutil -m cp -r build/img gs://public-tree-map/
      - store_artifacts:
          path: tmp/log.txt
          destination: log.txt

workflows:
  version: 2
  commit:
    jobs:
      - deploy:
          filters:
            branches:
              only:
              - master
              - test-circleci
  nightly:
    triggers:
      - schedule:
          # Midnight PST is 8am UTC
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - deploy